[alias]
e = "run --example"
tc = "test -- --nocapture"

[source."git+https://github.com/foundry-rs/foundry?tag=nightly-ad5ff80cc8576274bc20e3218bafd4c9d45994fb"]
git = "https://github.com/foundry-rs/foundry"
tag = "nightly-ad5ff80cc8576274bc20e3218bafd4c9d45994fb"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "foundry-rs-config"
