on: [push, pull_request, workflow_dispatch]

name: Foundry Compilers Aletheia

concurrency:
  group: ci-${{ github.ref }}-cargo
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Rust Nightly (2025-01-01)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-09-20
          override: true

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install JS Dependencies
        run: |
          pnpm install --prefix test-configs/hardhat-basic
          pnpm install --prefix test-configs/hardhat-mini
          npm install --prefix test-configs/hardhat-dupsource

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          cargo build
          cargo test -- --nocapture
